In [1]:
# import
import pandas as pd

In [2]:
# data ---> dict
data = {
    'name':['suhani','subhi','kartik','jiger','purvi'],
    'marks':[90,80,70,60,50]
}

print(data)

{'name': ['suhani', 'subhi', 'kartik', 'jiger', 'purvi'], 'marks': [90, 80, 70, 60, 50]}

In [3]:
df = pd.DataFrame(data)
df

     name  marks
0  suhani     90
1   subhi     80
2  kartik     70
3   jiger     60
4   purvi     50

In [4]:
df['name']

0    suhani
1     subhi
2    kartik
3     jiger
4     purvi
Name: name, dtype: str

In [5]:
type(df['name'])

pandas.Series

In [6]:
type(df)

pandas.DataFrame

In [7]:
## comma seprated values file ---> csv file

In [8]:
# how to load a csv file in pandas
df = pd.read_csv('mckinsey.csv')
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [9]:
df.head() # by default it will show 5 rows

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [10]:
df.head(12) # show top 12 rows

        country  year  population continent  life_exp     gdp_cap
0   Afghanistan  1952     8425333      Asia    28.801  779.445314
1   Afghanistan  1957     9240934      Asia    30.332  820.853030
2   Afghanistan  1962    10267083      Asia    31.997  853.100710
3   Afghanistan  1967    11537966      Asia    34.020  836.197138
4   Afghanistan  1972    13079460      Asia    36.088  739.981106
5   Afghanistan  1977    14880372      Asia    38.438  786.113360
6   Afghanistan  1982    12881816      Asia    39.854  978.011439
7   Afghanistan  1987    13867957      Asia    40.822  852.395945
8   Afghanistan  1992    16317921      Asia    41.674  649.341395
9   Afghanistan  1997    22227415      Asia    41.763  635.341351
10  Afghanistan  2002    25268405      Asia    42.129  726.734055
11  Afghanistan  2007    31889923      Asia    43.828  974.580338

In [11]:
df.tail() # by default it will show last 5 rows

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [12]:
df.tail(12)

       country  year  population continent  life_exp     gdp_cap
1692  Zimbabwe  1952     3080907    Africa    48.451  406.884115
1693  Zimbabwe  1957     3646340    Africa    50.469  518.764268
1694  Zimbabwe  1962     4277736    Africa    52.358  527.272182
1695  Zimbabwe  1967     4995432    Africa    53.995  569.795071
1696  Zimbabwe  1972     5861135    Africa    55.635  799.362176
1697  Zimbabwe  1977     6642107    Africa    57.674  685.587682
1698  Zimbabwe  1982     7636524    Africa    60.363  788.855041
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

### dataframe --> 2d or more then 2d (multiple rows and columns)

In [13]:
type(df)

pandas.DataFrame

In [14]:
# shape ---> rows and columns
df.shape

(1704, 6)

In [15]:
# info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   str
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   str
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 80.0 KB

In [16]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='str')

In [17]:
df.values

array([['Afghanistan', 1952, 8425333, 'Asia', 28.801, 779.4453145],
       ['Afghanistan', 1957, 9240934, 'Asia', 30.332, 820.8530296],
       ['Afghanistan', 1962, 10267083, 'Asia', 31.997, 853.10071],
       ...,
       ['Zimbabwe', 1997, 11404948, 'Africa', 46.809, 792.4499603],
       ['Zimbabwe', 2002, 11926563, 'Africa', 39.989, 672.0386227],
       ['Zimbabwe', 2007, 12311143, 'Africa', 43.487, 469.7092981]],
      shape=(1704, 6), dtype=object)

In [18]:
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='str')

In [19]:
df['country'].head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: str

In [22]:
df[['country', 'year']].head()

       country  year
0  Afghanistan  1952
1  Afghanistan  1957
2  Afghanistan  1962
3  Afghanistan  1967
4  Afghanistan  1972

In [26]:
df['country'].unique()

<StringArray>
[       'Afghanistan',            'Albania',            'Algeria',
             'Angola',          'Argentina',          'Australia',
            'Austria',            'Bahrain',         'Bangladesh',
            'Belgium',
 ...
             'Uganda',     'United Kingdom',      'United States',
            'Uruguay',          'Venezuela',            'Vietnam',
 'West Bank and Gaza',        'Yemen, Rep.',             'Zambia',
           'Zimbabwe']
Length: 142, dtype: str

In [27]:
df['country'].value_counts()

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [29]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='str')

In [ ]:
df.rename({'country':'desh'},axis= 1) # axis = 1 ---> column wise, axis = 0 ---> row wise
# this is temporary change

             desh  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [31]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [33]:
df.rename({'country':'desh'},axis= 1,inplace = True) # axis = 1 ---> column wise, axis = 0 ---> row wise
# this is permanent change
df.head()

          desh  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [34]:
df

             desh  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [35]:
df.rename(columns={'desh':'country'},inplace = True)
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [36]:
df.drop('continent', axis=1)

          country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [37]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

### again if u want to delete permanent have to use inpalce =True

In [38]:
df['year+7']=df['year']+7
df.head()

       country  year  population continent  life_exp     gdp_cap  year+7
0  Afghanistan  1952     8425333      Asia    28.801  779.445314    1959
1  Afghanistan  1957     9240934      Asia    30.332  820.853030    1964
2  Afghanistan  1962    10267083      Asia    31.997  853.100710    1969
3  Afghanistan  1967    11537966      Asia    34.020  836.197138    1974
4  Afghanistan  1972    13079460      Asia    36.088  739.981106    1979

In [39]:
df['total_gdf'] = df['year'] * df['life_exp']
df.head()

,country,year,population,continent,life_exp,gdp_cap,year+7,total_gdf
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,1959,56219.552
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,1964,59359.724
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,1969,62778.114
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,1974,66917.340
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,1979,71165.536

In [40]:
df.drop(columns ={'year+7', 'total_gdf'},inplace = True)
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106