In [1]:
# import
import pandas as pd

In [2]:
# data ---> dict
data = {
    'name':['suhani','subhi','kartik','jiger','purvi'],
    'marks':[90,80,70,60,50]
}

print(data)

{'name': ['suhani', 'subhi', 'kartik', 'jiger', 'purvi'], 'marks': [90, 80, 70, 60, 50]}

In [3]:
df = pd.DataFrame(data)
df

     name  marks
0  suhani     90
1   subhi     80
2  kartik     70
3   jiger     60
4   purvi     50

In [13]:
df['name']

0    suhani
1     subhi
2    kartik
3     jiger
4     purvi
Name: name, dtype: str

In [14]:
type(df['name'])

pandas.Series

In [4]:
type(df)

pandas.DataFrame

In [ ]:
## comma seprated values file ---> csv file

In [16]:
# how to load a csv file in pandas
df = pd.read_csv('mckinsey.csv')
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.head() # by default it will show 5 rows

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [19]:
df.head(12) # show top 12 rows

        country  year  population continent  life_exp     gdp_cap
0   Afghanistan  1952     8425333      Asia    28.801  779.445314
1   Afghanistan  1957     9240934      Asia    30.332  820.853030
2   Afghanistan  1962    10267083      Asia    31.997  853.100710
3   Afghanistan  1967    11537966      Asia    34.020  836.197138
4   Afghanistan  1972    13079460      Asia    36.088  739.981106
5   Afghanistan  1977    14880372      Asia    38.438  786.113360
6   Afghanistan  1982    12881816      Asia    39.854  978.011439
7   Afghanistan  1987    13867957      Asia    40.822  852.395945
8   Afghanistan  1992    16317921      Asia    41.674  649.341395
9   Afghanistan  1997    22227415      Asia    41.763  635.341351
10  Afghanistan  2002    25268405      Asia    42.129  726.734055
11  Afghanistan  2007    31889923      Asia    43.828  974.580338

In [20]:
df.tail() # by default it will show last 5 rows

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [21]:
df.tail(12)

       country  year  population continent  life_exp     gdp_cap
1692  Zimbabwe  1952     3080907    Africa    48.451  406.884115
1693  Zimbabwe  1957     3646340    Africa    50.469  518.764268
1694  Zimbabwe  1962     4277736    Africa    52.358  527.272182
1695  Zimbabwe  1967     4995432    Africa    53.995  569.795071
1696  Zimbabwe  1972     5861135    Africa    55.635  799.362176
1697  Zimbabwe  1977     6642107    Africa    57.674  685.587682
1698  Zimbabwe  1982     7636524    Africa    60.363  788.855041
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298